name: CI

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3.4.1
        with:
          node-version-file: .nvmrc
      - name: build
        run: |
          npm ci
          npm test
          npm run prepack
          npm run dist
